/**
 * Long-form evergreen guides — US residential solar economics.
 * Hub pages that link deep into the state-by-state solar cost and savings data.
 * Each guide targets a high-intent keyword and answers a complete question.
 */

export interface Guide {
  slug: string;
  title: string;
  description: string;
  intro: string; // HTML
  sections: Array<{ heading: string; html: string }>;
  faqs: Array<{ question: string; answer: string }>;
  category: string;
  updatedAt: string;
}

const u = '2026-04-10';

export const guides: Guide[] = [
  {
    slug: 'solar-cost-per-watt-by-state',
    title: 'Solar Cost Per Watt by State: 2025 Prices from $2.50 to $4.50/W',
    description: 'State-by-state breakdown of residential solar costs per watt based on SEIA/Wood Mackenzie data. Why prices vary by 80% across states and what drives the difference.',
    category: 'Costs',
    updatedAt: u,
    intro: `<p>The average US residential solar installation costs $3.00-$3.50 per watt before the federal tax credit in 2025. But that national average hides an 80% spread: homeowners in Arizona pay as little as $2.50/W while those in Connecticut or Rhode Island pay $4.00-$4.50/W for functionally identical equipment. This guide breaks down why costs vary so dramatically and what you can actually control.</p><p>All pricing data comes from SEIA/Wood Mackenzie US Solar Market Insight reports and the Lawrence Berkeley National Lab Tracking the Sun dataset, which tracks over 2.5 million residential installations.</p>`,
    sections: [
      {
        heading: 'State-by-state cost per watt (top 20 markets)',
        html: `<p>Median installed cost per watt for a 7 kW residential system, before federal ITC (LBNL Tracking the Sun, 2024 data):</p><ul><li><strong>Arizona</strong> — $2.53/W (mature market, high competition, streamlined permitting)</li><li><strong>Texas</strong> — $2.61/W (large market, no state incentive but high competition)</li><li><strong>Nevada</strong> — $2.68/W (abundant sun drives installer density)</li><li><strong>Florida</strong> — $2.72/W (large market, property tax exemption for solar)</li><li><strong>California</strong> — $2.89/W (largest market but high labor costs offset competition benefits)</li><li><strong>Colorado</strong> — $2.95/W (strong market, Xcel Energy rebates in some territories)</li><li><strong>North Carolina</strong> — $2.98/W (utility-scale growth created residential installer pipeline)</li><li><strong>Georgia</strong> — $3.05/W (growing market, minimal state incentives)</li><li><strong>Virginia</strong> — $3.10/W (newer market, growing competition)</li><li><strong>Utah</strong> — $3.12/W (high sun, moderate installer competition)</li><li><strong>New Jersey</strong> — $3.18/W (dense market, good incentives offset higher costs)</li><li><strong>Maryland</strong> — $3.22/W (SRECs add value, moderate installer density)</li><li><strong>Illinois</strong> — $3.35/W (SREC program drives demand but shorter sun hours)</li><li><strong>New York</strong> — $3.48/W (high labor costs, complex permitting in NYC metro)</li><li><strong>Pennsylvania</strong> — $3.52/W (moderate market size, SREC value declining)</li><li><strong>Massachusetts</strong> — $3.65/W (SMART program incentives but high labor and permitting costs)</li><li><strong>Oregon</strong> — $3.72/W (smaller market, lower sun hours increase cost per kWh produced)</li><li><strong>Connecticut</strong> — $3.95/W (small state, fewer installers, high labor)</li><li><strong>Rhode Island</strong> — $4.10/W (smallest state market, limited competition)</li><li><strong>Hawaii</strong> — $4.45/W (island logistics, shipping costs for equipment, high labor)</li></ul>`,
      },
      {
        heading: 'Why costs vary: the 5 factors',
        html: `<p>The $2.00/W spread between cheapest and most expensive states breaks down into five components:</p><ol><li><strong>Soft costs (40-55% of total)</strong>: permitting fees, inspection costs, interconnection applications, sales/marketing, and overhead. These vary the most between states. In Arizona, a residential permit costs $200-$500 and takes 3-5 days. In Connecticut, it can cost $1,000-$2,000 and take 4-8 weeks. NREL estimates soft costs account for 64% of the price difference between the cheapest and most expensive states.</li><li><strong>Labor (20-25%)</strong>: installer wages track local construction labor markets. A crew in Phoenix earns $18-$24/hour; a crew in Boston earns $28-$38/hour. Union vs non-union markets add another 15-20% differential.</li><li><strong>Equipment (20-25%)</strong>: hardware costs are relatively uniform nationwide — panels ($0.25-$0.40/W), inverters ($0.15-$0.25/W), racking ($0.10-$0.15/W). The equipment component varies less than 15% between states.</li><li><strong>Market competition</strong>: states with 50+ active residential installers see 10-15% lower prices than states with fewer than 10. Comparison shopping drives efficiency. Arizona has over 200 active installers; Rhode Island has about 15.</li><li><strong>Electricity rates</strong>: counterintuitively, states with high electricity rates (CT, MA, NY) have higher solar prices because the value proposition is strong enough that installers can charge more and still deliver good payback. In cheap-power states, installers must compete on price to make the economics work.</li></ol>`,
      },
      {
        heading: 'The cost trend: 2015 to 2025',
        html: `<p>Residential solar prices have declined 35% over the past decade, but the pace has slowed:</p><ul><li><strong>2015</strong>: national median $3.80/W</li><li><strong>2017</strong>: $3.40/W (-11%)</li><li><strong>2019</strong>: $3.15/W (-7%)</li><li><strong>2021</strong>: $2.95/W (-6%), temporarily reversed by supply chain disruptions</li><li><strong>2022</strong>: $3.20/W (supply chain spike, module tariff uncertainty)</li><li><strong>2023</strong>: $3.10/W (supply chain recovery, module prices crashed globally)</li><li><strong>2024</strong>: $3.05/W (continued soft cost reduction)</li><li><strong>2025</strong>: $2.95-$3.10/W (projected, driven by installer efficiency gains)</li></ul><p>Module (panel) prices have fallen 90% since 2010, from $2.00/W to $0.25/W. The remaining cost reduction must come from soft costs and labor efficiency, which decline much more slowly. NREL projects residential solar will reach $2.00/W by 2030 under its optimistic scenario, but this requires significant permitting reform.</p>`,
      },
      {
        heading: 'How to get below your state average',
        html: `<p>Homeowners can typically beat their state's median price by 10-20% with these tactics:</p><ul><li><strong>Get 3-5 quotes</strong>: the single most effective strategy. EnergySage data shows homeowners who compare 3+ quotes save an average of 10% vs those who accept the first offer. National installers (SunRun, Sunpower) are typically 15-30% more expensive than local companies.</li><li><strong>Choose standard equipment</strong>: premium panels (SunPower Maxeon, REC Alpha) cost $0.10-$0.20/W more than Tier 1 alternatives (Longi, Trina, Canadian Solar) with similar 25-year warranty coverage. Unless you have severe space constraints, standard panels deliver better economics.</li><li><strong>Pay cash or get a home equity loan</strong>: solar-specific loans often carry dealer fees of $0.50-$1.00/W that are baked into the total cost. A HELOC at 7% is almost always cheaper than a solar loan at "2.99%" that includes a 25% dealer fee.</li><li><strong>Time your purchase</strong>: Q4 (October-December) is typically 5-8% cheaper than Q2 (April-June) because installers are trying to fill year-end capacity before the seasonal slowdown.</li></ul>`,
      },
      {
        heading: 'Cost per watt vs cost per kWh: the metric that actually matters',
        html: `<p>Cost per watt measures what you pay for the system. Cost per kWh (levelized cost of energy, or LCOE) measures what you pay for the electricity it produces over its lifetime. The distinction matters because sun exposure varies by state:</p><ul><li><strong>Arizona</strong>: $2.53/W, 1,800 kWh/kW/year production → LCOE $0.056/kWh over 25 years</li><li><strong>Massachusetts</strong>: $3.65/W, 1,200 kWh/kW/year → LCOE $0.122/kWh</li><li><strong>Oregon</strong>: $3.72/W, 1,100 kWh/kW/year → LCOE $0.135/kWh</li></ul><p>Even though Massachusetts has higher cost per watt, the LCOE of $0.122/kWh is still below the retail electricity rate of $0.33/kWh — a 63% savings. In Oregon, the LCOE of $0.135/kWh compares to a retail rate of $0.13/kWh — essentially break-even. This is why solar adoption is high in the Northeast despite higher costs: the savings margin depends on the spread between LCOE and grid electricity price, not on LCOE alone.</p>`,
      },
    ],
    faqs: [
      { question: 'What is a good price per watt for solar in 2025?', answer: 'Below your state median is a good target. For Sunbelt states (AZ, TX, FL, NV), aim for $2.40-$2.70/W. For mid-cost states (CA, CO, NC, NJ), target $2.80-$3.20/W. For high-cost states (MA, CT, NY), $3.30-$3.80/W is competitive. These are pre-ITC prices for cash purchases without dealer fees.' },
      { question: 'Does the federal tax credit reduce the cost per watt?', answer: 'Yes. The 30% ITC effectively reduces your net cost per watt by 30%. A system priced at $3.00/W becomes $2.10/W after the credit. However, you must have sufficient federal tax liability to claim the full credit in one year, or carry the remainder forward to the next tax year.' },
      { question: 'Why is solar more expensive in the Northeast?', answer: 'Three factors compound: higher labor costs (construction wages 40-60% above Sunbelt), more complex permitting (historical building codes, underground conduit requirements in many jurisdictions), and smaller market size reducing installer competition. Equipment costs are nearly identical nationwide.' },
      { question: 'Are solar prices still dropping?', answer: 'Module prices have essentially bottomed out at $0.25-$0.30/W for Tier 1 panels. Further installed-cost reductions depend on soft cost reform (permitting, inspection, interconnection) and labor productivity gains. NREL projects 2-4% annual decline through 2030, much slower than the 10-15% annual declines of 2010-2018.' },
      { question: 'Should I wait for prices to drop further?', answer: 'For most homeowners, no. The 30% ITC is guaranteed through 2032 but steps down to 26% in 2033 and 22% in 2034. At current cost reduction rates of 2-4% per year, waiting one year saves roughly $200-$400 on a 7 kW system but costs you a year of electricity savings ($1,200-$2,000). The math favors installing now unless you expect to move within 5 years.' },
      { question: 'What size system does the average home need?', answer: 'The average US home uses about 10,500 kWh per year. In Arizona (1,800 kWh/kW production), a 6 kW system covers that. In Massachusetts (1,200 kWh/kW), you need a 9 kW system for the same production. Most residential systems are 5-12 kW, depending on electricity usage, roof space, and local sun hours.' },
      { question: 'Is leasing cheaper than buying per watt?', answer: 'Solar leases and PPAs do not have a cost-per-watt metric because you do not own the system. Instead, you pay per kWh generated, typically $0.10-$0.18/kWh with a 1-3% annual escalator. Over 25 years, leasing typically costs 40-60% more than buying with cash because the leasing company keeps the ITC, depreciation, and any SREC revenue.' },
    ],
  },
  {
    slug: 'federal-solar-itc-30-percent',
    title: 'The 30% Federal Solar Tax Credit: How to Claim It and Common Mistakes',
    description: 'Complete guide to the IRS Section 48 residential solar Investment Tax Credit — 30% through 2032, eligible costs, Form 5695, and the mistakes that delay or reduce your credit.',
    category: 'Incentives',
    updatedAt: u,
    intro: `<p>The federal solar Investment Tax Credit (ITC) reduces your federal income tax by 30% of the total cost of a residential solar energy system installed between 2022 and 2032. On a $21,000 system, that is a $6,300 reduction in your tax bill. The Inflation Reduction Act of 2022 extended and expanded this credit, but the rules have nuances that trip up thousands of filers every year. This guide covers everything you need to know to claim the full amount correctly.</p>`,
    sections: [
      {
        heading: 'ITC timeline and phase-down schedule',
        html: `<p>The solar ITC has changed several times. Current schedule per the Inflation Reduction Act (IRA):</p><ul><li><strong>2022-2032</strong>: 30% of eligible costs (this is the current rate)</li><li><strong>2033</strong>: 26% of eligible costs</li><li><strong>2034</strong>: 22% of eligible costs</li><li><strong>2035 and after</strong>: 0% for residential (the credit expires unless Congress renews it)</li></ul><p>The credit applies based on when the system is "placed in service" — meaning it is installed, connected, and capable of generating electricity. If you sign a contract in 2032 but the system is not operational until 2033, you get the 2033 rate (26%), not the 2032 rate (30%).</p><p>There is no maximum dollar amount for the residential ITC. A $50,000 system qualifies for a $15,000 credit. A $100,000 system qualifies for $30,000. This differs from some state credits that cap at a fixed dollar amount.</p>`,
      },
      {
        heading: 'What costs are eligible',
        html: `<p>The ITC covers the full cost of the solar energy system, including:</p><ul><li><strong>Solar panels and inverters</strong> — the hardware itself, including microinverters or string inverters.</li><li><strong>Racking and mounting equipment</strong> — roof mounts, ground mounts, ballasted systems.</li><li><strong>Balance of system</strong> — wiring, conduit, junction boxes, disconnects, monitoring equipment.</li><li><strong>Battery storage</strong> — as of the IRA, standalone battery storage qualifies for the 30% credit even without solar panels, as long as the battery has at least 3 kWh capacity. Previously, batteries had to be charged 100% by solar to qualify.</li><li><strong>Installation labor</strong> — the cost of the crew installing the system.</li><li><strong>Permitting and inspection fees</strong> — local government fees related to the solar installation.</li><li><strong>Sales tax</strong> — if applicable, the sales tax paid on the system is part of the eligible cost basis.</li><li><strong>Roof work directly related to solar</strong> — if your installer must reinforce or repair a section of roof specifically to support the solar array, that cost is eligible. A full roof replacement is NOT eligible even if done at the same time.</li></ul><p>Not eligible: the cost of a new roof (unless structural work is specifically for the solar array), tree removal, landscaping, or any costs not directly related to the solar energy system.</p>`,
      },
      {
        heading: 'How to claim it on your tax return',
        html: `<p>The ITC is claimed on IRS Form 5695 (Residential Energy Credits), which flows to Schedule 3 of your Form 1040:</p><ol><li><strong>Line 1</strong>: Enter the total eligible cost of your solar energy system.</li><li><strong>Line 5</strong>: Multiply by 0.30 (30%) to calculate your credit.</li><li><strong>Line 14</strong>: Your credit is limited to your total federal tax liability for the year. If your tax liability is $4,000 and your credit is $6,300, you claim $4,000 in the current year.</li><li><strong>Carryforward</strong>: the remaining $2,300 carries forward to the next tax year. The IRA allows unlimited carryforward for residential solar credits (this was not always the case — pre-2022 rules limited carryforward).</li></ol><p>Important: the ITC is a tax credit, not a deduction. It reduces your tax liability dollar-for-dollar. A $6,300 credit saves you $6,300 in taxes, regardless of your tax bracket. This makes it far more valuable than a deduction of the same amount.</p>`,
      },
      {
        heading: 'Common mistakes that reduce or delay your credit',
        html: `<ol><li><strong>Confusing tax liability with refund</strong>: the credit reduces what you owe, not what you have withheld. If you normally get a $2,000 refund and your tax liability is $8,000, you can claim the full $6,300 credit (your refund becomes $8,300). If your total tax liability is only $3,000, you claim $3,000 this year and carry forward the rest.</li><li><strong>Missing the "placed in service" date</strong>: if your system was installed in December but not granted permission to operate (PTO) by your utility until January, the IRS considers it placed in service in January. Document the PTO date carefully.</li><li><strong>Including ineligible costs</strong>: full roof replacements, electrical panel upgrades not required by the solar system, and tree removal do not qualify. Some installers bundle these into the solar invoice, which can trigger IRS scrutiny. Request an itemized invoice that separates solar-specific costs.</li><li><strong>Leased systems do not qualify</strong>: if you lease solar panels or have a PPA (power purchase agreement), the leasing company claims the ITC, not you. You get no federal tax credit. This is why leased solar is cheaper upfront but more expensive over the system lifetime.</li><li><strong>Forgetting battery storage</strong>: if you added battery storage as part of or after your solar installation (2023+), it qualifies for the 30% credit separately. Many homeowners forget to include battery costs on Form 5695.</li><li><strong>Filing amended returns too late</strong>: if you forgot to claim the credit, you can file an amended return (Form 1040-X) for up to 3 years after the original filing deadline. For a system installed in 2024, you have until April 2028 to amend your 2024 return.</li></ol>`,
      },
      {
        heading: 'ITC interaction with state incentives',
        html: `<p>The federal ITC and state incentives can stack, but the interaction is not always straightforward:</p><ul><li><strong>State tax credits</strong>: these do NOT reduce your federal ITC basis. If you receive a $2,000 state tax credit, your federal ITC is still calculated on the full system cost.</li><li><strong>State rebates (upfront cash)</strong>: if you receive a cash rebate from a state program or utility, the IRS generally considers this a reduction in your cost basis. Example: $21,000 system minus a $3,000 utility rebate = $18,000 cost basis for the federal ITC ($5,400 credit instead of $6,300). This is the IRS's current position per Notice 2013-70, though enforcement is inconsistent.</li><li><strong>SRECs (Solar Renewable Energy Certificates)</strong>: income from selling SRECs is taxable as ordinary income but does NOT reduce your ITC cost basis. You get the full ITC AND the SREC revenue.</li><li><strong>Net metering credits</strong>: utility bill credits from net metering are not taxable income and do not affect your ITC.</li></ul><p>The interaction between utility rebates and the ITC is the most commonly misunderstood tax issue in residential solar. If you receive a utility rebate, consult a tax professional about whether to reduce your cost basis.</p>`,
      },
      {
        heading: 'Special situations',
        html: `<p>Several less-common scenarios have specific ITC rules:</p><ul><li><strong>New construction</strong>: solar installed on a new home you are building qualifies for the ITC. The cost must be separated from the home purchase price — get an itemized invoice from the builder.</li><li><strong>Second homes</strong>: the ITC applies to solar on second homes (vacation homes) that you own. It does NOT apply to rental properties (those use the Section 48 commercial credit with different rules).</li><li><strong>Community solar</strong>: if you purchase (not subscribe to) a share of a community solar project, you may be eligible for the ITC on your ownership share. Subscription-based community solar does not qualify.</li><li><strong>Ground-mounted systems</strong>: fully eligible, same as rooftop. The additional cost of ground mounting (concrete piers, trenching) is part of the eligible cost basis.</li><li><strong>System expansion</strong>: if you add panels or battery storage in a later year, the new equipment qualifies for the ITC at the rate in effect when it is placed in service, independent of your original system.</li></ul>`,
      },
    ],
    faqs: [
      { question: 'Is the 30% solar tax credit a refund?', answer: 'No. It is a nonrefundable tax credit that reduces your federal tax liability. If you owe $5,000 in federal taxes, a $6,300 credit reduces your liability to $0 and carries the remaining $1,300 forward to the next year. It does not generate a refund beyond what you would otherwise receive from withholding.' },
      { question: 'Can I claim the solar tax credit if I have no tax liability?', answer: 'You need at least some federal tax liability to benefit. If your tax liability is $0 (common for retirees with only Social Security income), the credit carries forward but may never be usable. In this case, a solar lease or PPA (where the company claims the credit) may provide better economics.' },
      { question: 'Does the solar tax credit apply to battery storage?', answer: 'Yes, as of the Inflation Reduction Act (2022). Standalone battery storage with at least 3 kWh capacity qualifies for the 30% credit even without solar panels. Previously, batteries had to be charged exclusively by solar. This change made retrofitting existing solar systems with batteries significantly more affordable.' },
      { question: 'What happens to the tax credit if I sell my house?', answer: 'The ITC stays with the original taxpayer who installed the system. If you claimed the credit and sell the house within 5 years of installation, there is no clawback or recapture requirement for residential solar (unlike commercial solar). The new homeowner does not receive any remaining credit.' },
      { question: 'Can I claim the tax credit on a solar system I installed myself?', answer: 'Yes. DIY solar installations qualify for the ITC. However, only the cost of equipment and materials qualifies — you cannot value your own labor. Most DIY installations save on the labor component but forgo panel and inverter warranties that require professional installation.' },
      { question: 'Do I need to itemize deductions to claim the solar tax credit?', answer: 'No. The solar ITC is a tax credit, not a deduction. It is claimed on Form 5695 and flows to Schedule 3, which applies regardless of whether you take the standard deduction or itemize. This is one of the most common misconceptions about the credit.' },
      { question: 'How long does it take to get the solar tax credit?', answer: 'The credit applies when you file your annual tax return. If your system was placed in service in 2025, you claim the credit on your 2025 tax return filed in early 2026. If you owe taxes, the credit reduces your payment. If your withholding exceeds your reduced liability, the excess comes back as a refund — typically within 2-3 weeks of e-filing.' },
    ],
  },
  {
    slug: 'solar-panel-degradation-25-years',
    title: 'Solar Panel Degradation Over 25 Years: What the Data Actually Shows',
    description: 'NREL degradation studies show panels lose 0.5-0.8% output per year. What this means for 25-year production, warranties, and the difference between Tier 1 and Tier 2 panels.',
    category: 'Technology',
    updatedAt: u,
    intro: `<p>Solar panels do not last forever at full output. Every panel degrades — producing slightly less electricity each year as the silicon cells age. The question is how much and how fast. The National Renewable Energy Laboratory (NREL) has tracked degradation across thousands of installations over decades. This guide summarizes what the research shows and what it means for your long-term solar economics.</p>`,
    sections: [
      {
        heading: 'What degradation means in practice',
        html: `<p>Solar panel degradation is the gradual decline in electricity output over time, measured as a percentage loss per year. The physics:</p><ul><li><strong>Light-induced degradation (LID)</strong>: occurs in the first 1-3 days of sun exposure. Boron-doped silicon cells lose 1-3% of output as boron-oxygen complexes form. This is a one-time drop, not ongoing. Most manufacturers account for this in their initial rating.</li><li><strong>Potential-induced degradation (PID)</strong>: caused by voltage stress between cells and the grounded frame. Modern panels with anti-PID coatings are largely immune, but older or cheaper panels may lose 5-10% over their first 5 years.</li><li><strong>UV and thermal cycling</strong>: the long-term degradation mechanism. Daily temperature swings cause micro-cracks in solder joints and cell interconnects. UV exposure slowly degrades the encapsulant (EVA or POE). Combined, these produce the steady 0.5-0.8%/year decline that NREL documents.</li></ul><p>On a 7 kW system producing 10,500 kWh in year 1, a 0.5%/year degradation rate means 10,448 kWh in year 2, 10,396 kWh in year 3, and 9,275 kWh in year 25. Total cumulative production over 25 years: roughly 240,000 kWh vs 262,500 kWh with zero degradation — a 9% total loss.</p>`,
      },
      {
        heading: 'NREL degradation data by technology',
        html: `<p>NREL's 2023 meta-analysis of degradation studies covering 11,000+ systems found these median degradation rates:</p><ul><li><strong>Monocrystalline PERC (current standard)</strong>: 0.50%/year median, 0.70%/year 75th percentile. This is the technology in 85%+ of panels sold today (LONGi, Trina, Canadian Solar, JA Solar, Jinko).</li><li><strong>Heterojunction (HJT)</strong>: 0.40%/year median. Lower temperature coefficient reduces thermal stress. Used by REC (Alpha), Panasonic (EverVolt), and some premium lines.</li><li><strong>Interdigitated Back Contact (IBC)</strong>: 0.30-0.40%/year. SunPower Maxeon and Aiko use this technology. Highest efficiency, lowest degradation, highest cost.</li><li><strong>Thin-film (CdTe, CIGS)</strong>: 0.50-1.00%/year depending on manufacturer and climate. First Solar CdTe modules perform well in hot climates but degrade faster in cold/humid conditions.</li><li><strong>Older polycrystalline</strong>: 0.60-0.90%/year. This technology is largely phased out of the residential market but millions of older installations still use it.</li></ul><p>The key takeaway: for current-generation monocrystalline PERC panels from any Tier 1 manufacturer, expect 0.5%/year as a reasonable planning assumption. Premium HJT and IBC panels may degrade 20-30% slower, but the cost premium often exceeds the value of the additional energy.</p>`,
      },
      {
        heading: '25-year production projection',
        html: `<p>For a 7 kW system in a location with 1,500 kWh/kW/year (typical for the US mid-latitudes), here is what degradation means in dollar terms:</p><ul><li><strong>Year 1 production</strong>: 10,500 kWh</li><li><strong>Year 10 production (at 0.5%/year)</strong>: 10,038 kWh (4.4% decline from year 1)</li><li><strong>Year 20 production</strong>: 9,548 kWh (9.1% decline)</li><li><strong>Year 25 production</strong>: 9,275 kWh (11.7% decline)</li><li><strong>Cumulative 25-year production</strong>: approximately 247,000 kWh</li></ul><p>At an average avoided electricity cost of $0.16/kWh (national average residential rate), that is $39,500 in electricity savings over 25 years. Even at the higher degradation rate of 0.8%/year, cumulative production drops to about 233,000 kWh ($37,300) — only 6% less lifetime value.</p><p>The financial impact of degradation is real but modest. The difference between a 0.5%/year panel and a 0.8%/year panel over 25 years is about $2,200 in electricity value — less than the typical price premium for a "premium" panel brand.</p>`,
      },
      {
        heading: 'What warranties actually cover',
        html: `<p>Solar panel warranties have two components, and understanding what each covers prevents nasty surprises:</p><ul><li><strong>Product warranty (10-25 years)</strong>: covers manufacturing defects — cracked cells, delamination, junction box failure, frame corrosion. Most Tier 1 manufacturers offer 12-15 years; premium brands (SunPower, REC, LG when active) offer 25 years. This is the warranty that matters for catastrophic failure.</li><li><strong>Performance warranty (25-30 years)</strong>: guarantees the panel will produce at least a specified percentage of its rated output. Typical: 84.8% at year 25 (which implies 0.55%/year degradation after the initial 2% year-1 LID drop). Premium: 92% at year 25 (SunPower Maxeon).</li></ul><p>Critical fine print:</p><ul><li>Performance warranty claims require independent testing to prove the panel is underperforming — this costs $200-$500 per panel and is the homeowner's burden. Few homeowners ever file performance warranty claims because the cost of proving the claim exceeds the value of one underperforming panel.</li><li>Product warranty often excludes "acts of God" (hail, lightning), improper installation, and cosmetic damage (micro-cracks that do not affect output).</li><li>If the manufacturer goes bankrupt, the warranty is worthless. More than 50 solar panel manufacturers have exited the market since 2015.</li></ul>`,
      },
      {
        heading: 'Tier 1 vs Tier 2 panels: does brand matter?',
        html: `<p>Bloomberg New Energy Finance classifies manufacturers into tiers based on bankability (financial stability and track record), not quality:</p><ul><li><strong>Tier 1</strong> (top 10-15 brands): LONGi, Trina, Canadian Solar, JA Solar, Jinko, REC, Qcells, First Solar, SunPower/Maxeon, Risen, Astronergy. These manufacturers have strong balance sheets, long track records, and panels that have been independently tested in the field for 5+ years with predictable degradation.</li><li><strong>Tier 2</strong> (next 30-50 brands): financially viable but with shorter track records or less independent field data. Degradation characteristics may be less well-documented.</li><li><strong>Tier 3</strong> (all others): small manufacturers, often white-labeling cells from larger producers. Warranty backing is the main risk — the company may not exist in 10 years.</li></ul><p>For a residential installation expected to last 25-30 years, using a Tier 1 panel is worth the $0.02-$0.05/W premium over Tier 2. The degradation rates are well-characterized, the product warranty is more likely to be honored, and the panels have higher resale value if you sell the home.</p>`,
      },
      {
        heading: 'Environmental factors that accelerate degradation',
        html: `<p>Not all installations degrade at the same rate. Environmental conditions matter:</p><ul><li><strong>High temperatures</strong>: panels in Phoenix (rooftop temps exceeding 165 F) degrade about 0.1%/year faster than panels in Seattle. The temperature coefficient is the key spec — standard PERC panels lose 0.35-0.40% output per degree C above 25 C during operation, plus faster long-term degradation.</li><li><strong>Humidity</strong>: coastal and Gulf Coast installations experience faster encapsulant degradation from moisture ingress. Florida installations show degradation rates about 0.1-0.2%/year higher than the NREL median.</li><li><strong>Snow load</strong>: repeated heavy snow loading can cause micro-cracks in cells, but modern panels are tested to 5,400 Pa (about 112 lbs/sq ft). Normal snow loads do not cause degradation; ice dam formation and improper snow raking do.</li><li><strong>Salt air</strong>: within 1 mile of the ocean, salt corrosion can attack frames and junction boxes. Look for IEC 61701 salt mist corrosion certification if you are near the coast.</li><li><strong>Soiling</strong>: dust, pollen, and bird droppings reduce output but are not degradation — they are reversible with rain or cleaning. In arid regions (Arizona, Central California), soiling can reduce annual output by 3-7% if panels are not cleaned periodically.</li></ul>`,
      },
    ],
    faqs: [
      { question: 'How long do solar panels actually last?', answer: 'Most Tier 1 panels will continue producing electricity for 30-40 years. The 25-year warranty period is a financial guarantee, not a physical lifespan. After 25 years, a panel degraded at 0.5%/year still produces 88% of its original output. Many early installations from the 1990s are still operational, producing 75-80% of rated output after 30+ years.' },
      { question: 'Is 0.5% degradation per year good or bad?', answer: 'It is the current industry median for modern monocrystalline PERC panels and is considered normal. Anything below 0.5% is above average (HJT and IBC panels). Anything above 0.8% suggests a potential quality issue or harsh environmental conditions. For financial planning, using 0.5%/year is a conservative and realistic assumption.' },
      { question: 'Do microinverters degrade differently than panels?', answer: 'Microinverters and string inverters are separate components with their own failure rates. String inverters typically last 10-15 years and need one replacement during the panel lifetime (cost: $1,500-$3,000). Microinverters (Enphase) are warrantied for 25 years and have lower failure rates but are more expensive to replace individually if they do fail.' },
      { question: 'Should I pay more for premium panels with lower degradation?', answer: 'Usually not, for purely financial reasons. The lifetime energy difference between a 0.5%/year panel and a 0.3%/year panel is about 3,500 kWh over 25 years on a 7 kW system — worth roughly $560 at average rates. Premium panels typically cost $700-$1,400 more for the same system size. The math rarely favors the premium unless you have severe space constraints and need maximum production per panel.' },
      { question: 'Can degradation be reversed?', answer: 'LID (light-induced degradation) can be partially reversed by a process called "dark annealing" — heating panels without light — but this is not practical in the field. PID can sometimes be reversed by isolating the system overnight. Normal UV and thermal degradation is irreversible. There is no maintenance procedure that restores lost output from aging.' },
      { question: 'How do I measure my panels degradation?', answer: 'Compare year-over-year production from your monitoring system (Enphase, SolarEdge, or inverter portal), normalized for weather differences. A 0.5% decline is difficult to detect in a single year because weather variation causes larger swings. After 5+ years, the trend becomes visible. For a precise measurement, hire an independent tester with IV curve tracing equipment.' },
      { question: 'Do bifacial panels degrade differently?', answer: 'Bifacial panels (with glass-glass construction instead of glass-backsheet) show slightly lower degradation rates in early studies — approximately 0.4%/year — because the glass rear protects against moisture ingress and UV damage better than polymer backsheets. However, long-term field data for bifacial residential installations is still limited (most were installed after 2020).' },
    ],
  },
  {
    slug: 'grid-tied-vs-off-grid-vs-hybrid',
    title: 'Grid-Tied vs Off-Grid vs Hybrid Solar: Which System Makes Sense?',
    description: 'Comparing the economics, requirements, and tradeoffs of grid-tied solar (cheapest), hybrid with battery backup (growing fast), and true off-grid (expensive and complex).',
    category: 'System Design',
    updatedAt: u,
    intro: `<p>Three fundamentally different solar system architectures serve three different needs. Grid-tied systems are the cheapest and most common, sending excess energy to the grid and pulling from it at night. Hybrid systems add a battery for backup power during outages. Off-grid systems eliminate the utility connection entirely. Each has dramatically different costs, complexity, and economics. This guide puts numbers on the decision.</p>`,
    sections: [
      {
        heading: 'Grid-tied solar: the default choice',
        html: `<p>Grid-tied systems connect directly to the utility grid through a bidirectional meter. When your panels produce more than you use, excess flows to the grid. When you need more than your panels produce (nighttime, cloudy days), you pull from the grid. Key economics:</p><ul><li><strong>Cost</strong>: $2.50-$3.50/W installed (varies by state). A 7 kW system: $17,500-$24,500 before the 30% ITC.</li><li><strong>Net metering</strong>: in states with 1:1 net metering (about 38 states), you receive a full retail credit for every kWh sent to the grid. This makes the grid function as a free, infinite battery — your excess summer production offsets winter deficit.</li><li><strong>No battery needed</strong>: the grid provides all your backup. This eliminates $10,000-$15,000 in battery costs.</li><li><strong>Payback period</strong>: 6-10 years in most states with net metering and the 30% ITC.</li><li><strong>Limitation</strong>: grid-tied systems shut off during power outages for safety (anti-islanding). Even if the sun is shining, your panels produce nothing during a blackout. This is the single reason many homeowners consider adding a battery.</li></ul>`,
      },
      {
        heading: 'Hybrid solar with battery: the growing middle ground',
        html: `<p>Hybrid systems combine grid-tied solar with one or more batteries (typically lithium iron phosphate, LFP) that provide backup during outages and can optimize time-of-use electricity rates. Economics:</p><ul><li><strong>Cost</strong>: $4.00-$5.50/W total installed (solar + battery). A 7 kW solar + 13.5 kWh battery (Tesla Powerwall class): $28,000-$38,500 before ITC. The battery alone adds $10,000-$15,000.</li><li><strong>Battery economics without outage value</strong>: in states with time-of-use rates (California NEM 3.0, Arizona, Nevada), a battery can arbitrage the rate difference — charging at midday ($0.08/kWh export rate) and discharging at evening peak ($0.35-$0.55/kWh). This can save $50-$100/month, producing a 10-15 year battery payback.</li><li><strong>Battery economics with outage value</strong>: if you experience 2+ outages per year lasting 4+ hours (common in Florida, Texas, California wildfire zones), the outage avoidance value can add $500-$2,000/year depending on what you would otherwise spend on a generator.</li><li><strong>Battery sizing</strong>: a single 13.5 kWh battery (Powerwall, Enphase 5P, Franklin WH) powers essential loads (refrigerator, lights, WiFi, phone charging) for 10-16 hours. Whole-home backup for HVAC, cooking, and EV charging requires 2-3 batteries ($20,000-$40,000).</li></ul>`,
      },
      {
        heading: 'Off-grid solar: the full independence path',
        html: `<p>Off-grid systems have no utility connection. All electricity comes from solar panels and batteries, often supplemented by a backup generator. This is a fundamentally different proposition:</p><ul><li><strong>Cost</strong>: $8.00-$15.00/W equivalent. A system to power a typical US home year-round requires 10-15 kW of solar, 40-60 kWh of battery storage, and a backup generator. Total: $60,000-$120,000.</li><li><strong>Oversizing requirement</strong>: because there is no grid fallback, the system must be designed for worst-case conditions (shortest winter days, consecutive cloudy days). This means installing 2-3x the solar capacity needed for average conditions.</li><li><strong>Generator backup</strong>: even large off-grid systems typically include a propane or diesel generator ($5,000-$15,000) for extended cloudy periods in winter. Running the generator 200-500 hours/year at $3-$5/hour adds $600-$2,500 in annual fuel costs.</li><li><strong>Maintenance burden</strong>: battery replacement every 10-15 years ($15,000-$30,000), generator maintenance, and system monitoring are the homeowner's responsibility. Grid-tied systems are essentially maintenance-free by comparison.</li><li><strong>When it makes sense</strong>: remote properties where the cost of running utility lines exceeds $30,000-$50,000 (typically more than 0.5 miles from existing infrastructure). In these cases, off-grid solar is cheaper than grid connection — the only situation where it wins economically.</li></ul>`,
      },
      {
        heading: 'Net metering: the policy that makes grid-tied dominant',
        html: `<p>Net metering policy is the single biggest factor in choosing between grid-tied and hybrid. The landscape in 2025:</p><ul><li><strong>Full 1:1 retail net metering (best for grid-tied)</strong>: still available in roughly 38 states. Your excess kWh is credited at the full retail rate. This makes grid-tied the clear winner economically.</li><li><strong>Reduced net metering</strong>: California's NEM 3.0 (April 2023) cut export credits from $0.30/kWh to $0.04-$0.08/kWh during midday, making batteries essential for good economics. Several other states (Nevada, Arizona, Hawaii) have moved in this direction.</li><li><strong>No net metering</strong>: a few states (parts of Idaho, South Dakota, Alabama under utility discretion) offer no net metering, making grid-tied solar much less attractive. Batteries become the only way to use solar production that exceeds real-time consumption.</li></ul><p>The trend is clear: utilities are pushing to reduce net metering rates, which will make hybrid systems more common over the next decade. In states that have already reduced net metering, battery attach rates have jumped from 10% to 50-70% within 2 years.</p>`,
      },
      {
        heading: 'Decision framework: which system for your situation',
        html: `<p>A practical decision tree:</p><ol><li><strong>Does your state have full 1:1 net metering?</strong> If yes, start with grid-tied. It has the best economics and shortest payback. Add a battery later if net metering policy changes or you want outage protection.</li><li><strong>Are you in a reduced net metering state (CA NEM 3.0, etc.)?</strong> A hybrid system with one battery makes financial sense. The battery shifts self-consumption to offset the low export rate.</li><li><strong>Do you experience frequent or extended outages?</strong> Add a battery to grid-tied regardless of net metering policy. Size for essential loads unless you have a medical device or other critical need for whole-home backup.</li><li><strong>Is your property remote with no grid access?</strong> Off-grid is your only option. Budget $60K-$120K, plan for generator backup, and size the system for winter worst-case.</li><li><strong>Do you have time-of-use electric rates?</strong> A battery can arbitrage the rate difference. Calculate the monthly savings vs battery cost — if payback is under 12 years, it is worth considering.</li></ol>`,
      },
      {
        heading: 'Battery technology comparison for hybrid and off-grid',
        html: `<p>The residential battery market in 2025 is dominated by lithium iron phosphate (LFP) chemistry:</p><ul><li><strong>Tesla Powerwall 3</strong>: 13.5 kWh usable, integrated inverter, $9,500-$12,000 installed. 10-year warranty, 70% capacity retention. The market benchmark.</li><li><strong>Enphase IQ Battery 5P</strong>: 5 kWh per unit (stack up to 4 = 20 kWh), modular, $6,000-$8,000 per unit installed. 15-year warranty. Best for Enphase microinverter ecosystems.</li><li><strong>Franklin WH aPower</strong>: 13.6 kWh, 200A whole-home backup capable, $12,000-$15,000 installed. 12-year warranty. Gaining market share rapidly.</li><li><strong>Sonnen ecoLinx</strong>: 10-20 kWh modular, smart home integration, $15,000-$25,000 installed. Premium positioning.</li></ul><p>All current residential batteries use LFP chemistry, which has no thermal runaway risk (unlike older NMC chemistry), a cycle life of 6,000-10,000 cycles, and a calendar life of 15-20 years. For off-grid systems requiring 40-60 kWh, budget $30,000-$50,000 for the battery bank alone.</p>`,
      },
    ],
    faqs: [
      { question: 'Can I add a battery to my existing grid-tied solar system?', answer: 'Yes, and this is increasingly common. The battery qualifies for the 30% ITC independently of your existing solar. Installation typically takes 1-2 days. If you have a string inverter, you may need a hybrid inverter upgrade ($2,000-$4,000 additional). If you have microinverters (Enphase), the Enphase IQ Battery integrates directly.' },
      { question: 'How much does a solar battery cost?', answer: 'A single residential battery (13-14 kWh usable) costs $10,000-$15,000 fully installed before the 30% ITC. After the ITC, net cost is $7,000-$10,500. Whole-home backup requiring 2-3 batteries costs $20,000-$40,000 before ITC.' },
      { question: 'Is off-grid solar worth it?', answer: 'Only if the cost of running utility lines to your property exceeds $30,000-$50,000 (roughly 0.5+ miles from existing infrastructure). For properties already connected to the grid, off-grid is 3-5x more expensive per kWh over the system lifetime due to oversizing, battery replacement, and generator costs. It is a lifestyle choice, not an economic one.' },
      { question: 'What happens to grid-tied solar during a power outage?', answer: 'Without a battery, grid-tied solar systems shut off completely during outages. This is an NEC safety requirement called anti-islanding — it prevents solar from backfeeding power onto lines that utility workers are repairing. Adding a battery enables your solar to operate in "island mode" during outages, powering your home independently.' },
      { question: 'How long will a solar battery power my home during an outage?', answer: 'A 13.5 kWh battery powering essential loads (refrigerator 150W, WiFi router 15W, lights 100W, phone charging 20W = ~285W) lasts about 40-45 hours. If you add HVAC (2,000-3,000W), runtime drops to 4-6 hours. With solar recharging during the day, a single battery can sustain essential loads indefinitely in sunny conditions.' },
      { question: 'What is NEM 3.0 and how does it affect my decision?', answer: 'NEM 3.0 is California net metering policy effective April 2023. It reduced solar export credits from ~$0.30/kWh to $0.04-$0.08/kWh during midday hours while keeping high import rates at peak evening hours ($0.35-$0.55/kWh). This makes grid-tied-only solar much less attractive and batteries nearly essential for good economics in California. Other states are watching California as a policy model.' },
    ],
  },
  {
    slug: 'community-solar-without-panels',
    title: 'Community Solar: How to Get Solar Savings Without Rooftop Panels',
    description: 'Community solar lets renters and homeowners with unsuitable roofs subscribe to a local solar farm for 5-15% electricity savings. Available in 38+ states with no installation required.',
    category: 'Alternatives',
    updatedAt: u,
    intro: `<p>Roughly half of US households cannot install rooftop solar — they rent, live in apartments or condos, have shaded roofs, or face HOA restrictions. Community solar solves this by letting you subscribe to a share of a local solar farm and receive credits on your electricity bill. No panels on your roof, no installation, no equipment to maintain. As of 2025, community solar is available in 38+ states with over 7 GW of capacity serving 5 million households. This guide explains exactly how it works, what it costs, and whether it makes sense for you.</p>`,
    sections: [
      {
        heading: 'How community solar works',
        html: `<p>The basic model is straightforward:</p><ol><li><strong>A solar farm is built</strong> — typically 1-5 MW, located within the same utility territory as subscribers. Most are ground-mounted arrays on 5-20 acres.</li><li><strong>You subscribe to a share</strong> — either a fixed number of kW or a percentage of the farm's output sized to offset a portion of your electricity usage (typically 50-100%).</li><li><strong>The farm produces electricity</strong> — which is fed into the local grid. Your utility tracks your share of the production.</li><li><strong>You receive bill credits</strong> — your utility applies credits to your monthly bill for your share of the farm's output. Credits are typically at or near the retail electricity rate.</li><li><strong>You pay the solar farm operator</strong> — either a monthly subscription fee (less than the bill credits you receive) or a discounted per-kWh rate. The difference is your savings.</li></ol><p>Net effect: your total electricity cost drops by 5-15% with no upfront cost, no equipment, and the ability to cancel (typically with 30-90 days notice).</p>`,
      },
      {
        heading: 'Subscriber model vs ownership model',
        html: `<p>Community solar projects offer two participation structures:</p><ul><li><strong>Subscription (most common)</strong>: you pay a monthly fee or per-kWh rate that is lower than your utility rate. The solar farm operator owns the system, claims the ITC and depreciation, and passes some savings to you as a discount. Typical savings: 5-15% off your utility bill. No upfront cost. Cancel anytime (with notice period). You do NOT own any equipment or receive any tax benefits.</li><li><strong>Ownership</strong>: you purchase a share of the solar farm (typically $3,000-$10,000 for enough capacity to offset your usage). You may be eligible for the 30% ITC on your ownership share. Higher long-term savings (potentially 30-50% off utility costs) but with upfront capital, less liquidity, and the risk that the project underperforms.</li></ul><p>Subscription is the right choice for most people because it requires zero upfront cost and zero risk. Ownership makes sense only if you have the capital, plan to stay in the utility territory for 15+ years, and want to claim the ITC.</p>`,
      },
      {
        heading: 'State availability and program quality',
        html: `<p>Community solar availability varies dramatically by state, driven by enabling legislation and utility cooperation:</p><ul><li><strong>Best state programs (strong legislation + active markets)</strong>: New York (largest market, 2.5+ GW subscribed), Minnesota (pioneer state, robust program since 2014), Massachusetts (SMART program supports community solar), Illinois (Adjustable Block Program), Colorado (Xcel Energy community solar gardens), New Jersey (strong market since 2019), Maryland (expanding rapidly).</li><li><strong>Growing markets</strong>: California (CalCCA programs), Maine (nation's strongest community solar law, 2019), Virginia (Dominion Energy program), New Mexico, Connecticut, Oregon.</li><li><strong>Limited or no community solar</strong>: most Southeastern states (Alabama, Mississippi, Georgia, Tennessee, South Carolina, Louisiana) lack enabling legislation. Texas has community solar through co-ops but no statewide program. Idaho, Wyoming, and Montana have minimal activity.</li></ul><p>Check your state's status at the Coalition for Community Solar Access (CCSA) website or ask your utility directly. Availability changes rapidly — 8 states added or expanded programs in 2024 alone.</p>`,
      },
      {
        heading: 'Typical savings and contract terms',
        html: `<p>What to expect financially from a community solar subscription:</p><ul><li><strong>Savings rate</strong>: 5-15% off your current utility bill, guaranteed by the subscription agreement. The most common structure is a 10% discount — you pay 90 cents for every dollar of bill credits received.</li><li><strong>Contract length</strong>: most subscriptions are month-to-month or annual with auto-renewal. Some projects offer 10-20 year contracts with locked-in discount rates (better savings but less flexibility).</li><li><strong>Subscription size</strong>: typically sized to offset 80-100% of your annual electricity usage. If you use 10,000 kWh/year and your subscription share produces 10,000 kWh/year, your utility bill credits offset most of your charges.</li><li><strong>Example savings</strong>: on a $150/month electricity bill, a 10% community solar discount saves $15/month or $180/year. On a $250/month bill, savings are $25/month or $300/year. Over 10 years, that is $1,800-$3,000 with zero upfront cost.</li><li><strong>Savings ceiling</strong>: community solar savings are modest compared to rooftop ownership. A rooftop system typically saves 50-80% on electricity, while community solar saves 5-15%. The tradeoff is zero cost, zero risk, and zero maintenance.</li></ul>`,
      },
      {
        heading: 'Who should consider community solar',
        html: `<p>Community solar is the best option for households that cannot go rooftop:</p><ul><li><strong>Renters</strong> — 43 million US renter households cannot install rooftop solar. Community solar is the only way to access solar savings without owning property.</li><li><strong>Condo and apartment owners</strong> — shared roofs and HOA restrictions prevent individual installations. Community solar works regardless of building type.</li><li><strong>Homes with poor solar access</strong> — heavy tree cover, north-facing roofs, complex rooflines, or structural limitations make rooftop uneconomical. If your roof produces less than 80% of a clear-sky benchmark, community solar may deliver better savings.</li><li><strong>Low-income households</strong> — many state programs (NY, IL, MN, CO) reserve 20-40% of community solar capacity for low-income subscribers, often at enhanced discounts of 20-30%.</li><li><strong>People who plan to move</strong> — if you expect to relocate within 5 years, the 6-10 year payback of rooftop solar does not pencil. Community solar subscriptions transfer or cancel easily.</li></ul>`,
      },
      {
        heading: 'How to evaluate a community solar offer',
        html: `<p>Not all community solar programs are equal. Evaluate offers using these criteria:</p><ol><li><strong>Guaranteed savings rate</strong>: the contract should specify a minimum discount (e.g., "10% below utility rate"). Avoid programs that promise savings but do not guarantee them in writing.</li><li><strong>Cancellation terms</strong>: month-to-month is ideal. Acceptable: annual with 30-60 day notice. Red flag: long-term contracts with early termination fees exceeding one month's savings.</li><li><strong>Credit mechanism</strong>: virtual net metering (credits appear directly on your utility bill) is the cleanest. Some programs issue separate checks or credits, which is more complex and can create timing mismatches.</li><li><strong>Escalator clauses</strong>: some subscriptions include 1-3% annual price increases. Make sure your savings rate is calculated after the escalator, not before. A 10% savings with a 3% escalator may shrink to 4% savings by year 10 if utility rates do not rise proportionally.</li><li><strong>Project location and utility match</strong>: the solar farm must be in your utility's service territory. Cross-utility subscriptions do not work because the credit mechanism depends on your specific utility's billing system.</li></ol>`,
      },
    ],
    faqs: [
      { question: 'Do I need to own my home for community solar?', answer: 'No. Renters, apartment dwellers, and condo owners can subscribe to community solar. You only need an electricity account with a participating utility. This is the primary advantage of community solar over rooftop installation.' },
      { question: 'Is there an upfront cost for community solar?', answer: 'For subscription-based programs (the most common type), there is no upfront cost. You simply pay a monthly rate that is lower than your utility bill would otherwise be. Ownership-based programs do require an upfront purchase of a share, typically $3,000-$10,000.' },
      { question: 'How much can I save with community solar?', answer: 'Typical savings are 5-15% off your electricity bill. On a $150/month bill, that is $9-$23/month or $108-$270/year. Savings are real but modest compared to rooftop solar (50-80% savings). The appeal is zero cost, zero risk, and zero installation.' },
      { question: 'What happens if I move?', answer: 'Most community solar subscriptions can be transferred to a new address within the same utility territory or cancelled with 30-90 days notice. If you move out of the utility territory, you can typically cancel without penalty. Check your specific contract terms before signing.' },
      { question: 'Is community solar available in my state?', answer: 'As of 2025, community solar programs are active in 38+ states plus DC. The strongest markets are New York, Minnesota, Massachusetts, Illinois, Colorado, New Jersey, and Maryland. States without enabling legislation — mainly in the Southeast — have limited or no community solar options. Check with your utility or visit the CCSA state policy map for current availability.' },
      { question: 'Can I get community solar and rooftop solar?', answer: 'Technically yes, but it rarely makes sense. Most utilities only allow community solar credits to offset the portion of your bill not already covered by rooftop net metering. If your rooftop system covers 100% of your usage, there is nothing for community solar credits to offset. Community solar is best for households that cannot or choose not to install rooftop panels.' },
      { question: 'What is the difference between community solar and green energy programs?', answer: 'Green energy programs (offered by many utilities) charge you a premium to buy Renewable Energy Certificates (RECs), which support renewable generation somewhere in the country. Your bill goes up. Community solar credits your bill for electricity generated by a specific local solar farm. Your bill goes down. Community solar provides direct financial savings; green energy programs are a cost-added choice.' },
    ],
  },
];

export function getAllGuides(): Guide[] {
  return guides;
}

export function getGuideBySlug(slug: string): Guide | undefined {
  return guides.find((g) => g.slug === slug);
}
